#!/usr/bin/env bash

PROJ_DIR=$(git rev-parse --show-toplevel)

echo
xmverilog +xmnowarn+DSEM2009 +xmnowarn+DSEMEL -q -clean -y ${PROJ_DIR}/session3-part2/design/ -y ${PROJ_DIR}/session3-part2/design/system/ +libext+.sv +incdir+${PROJ_DIR}/session3-part2/design/ ${PROJ_DIR}/session3-part2/testbench/system_tb.sv
echo
